# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import template_pb2 as template__pb2


class TemplateStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateTemplate = channel.unary_unary(
        '/template.Template/GenerateTemplate',
        request_serializer=template__pb2.GenerateTemplateRequest.SerializeToString,
        response_deserializer=template__pb2.GenerateTemplateResponse.FromString,
        )


class TemplateServicer(object):

  def GenerateTemplate(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemplateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateTemplate,
          request_deserializer=template__pb2.GenerateTemplateRequest.FromString,
          response_serializer=template__pb2.GenerateTemplateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'template.Template', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
