# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='template.proto',
  package='template',
  syntax='proto3',
  serialized_pb=_b('\n\x0etemplate.proto\x12\x08template\x1a\x0b\x65rror.proto\"\x91\x01\n\x17GenerateTemplateRequest\x12\x12\n\ntemplateId\x18\x01 \x01(\t\x12:\n\x06params\x18\x02 \x03(\x0b\x32*.template.GenerateTemplateRequest.KeyValue\x1a&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"Y\n\x18GenerateTemplateResponse\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0f.template.ErrorH\x00\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x42\t\n\x07\x63ontent2g\n\x08Template\x12[\n\x10GenerateTemplate\x12!.template.GenerateTemplateRequest\x1a\".template.GenerateTemplateResponse(\x01\x62\x06proto3')
  ,
  dependencies=[error__pb2.DESCRIPTOR,])




_GENERATETEMPLATEREQUEST_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='template.GenerateTemplateRequest.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='template.GenerateTemplateRequest.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='template.GenerateTemplateRequest.KeyValue.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=187,
)

_GENERATETEMPLATEREQUEST = _descriptor.Descriptor(
  name='GenerateTemplateRequest',
  full_name='template.GenerateTemplateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='templateId', full_name='template.GenerateTemplateRequest.templateId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='template.GenerateTemplateRequest.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GENERATETEMPLATEREQUEST_KEYVALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=187,
)


_GENERATETEMPLATERESPONSE = _descriptor.Descriptor(
  name='GenerateTemplateResponse',
  full_name='template.GenerateTemplateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='template.GenerateTemplateResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='template.GenerateTemplateResponse.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='template.GenerateTemplateResponse.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=189,
  serialized_end=278,
)

_GENERATETEMPLATEREQUEST_KEYVALUE.containing_type = _GENERATETEMPLATEREQUEST
_GENERATETEMPLATEREQUEST.fields_by_name['params'].message_type = _GENERATETEMPLATEREQUEST_KEYVALUE
_GENERATETEMPLATERESPONSE.fields_by_name['error'].message_type = error__pb2._ERROR
_GENERATETEMPLATERESPONSE.oneofs_by_name['content'].fields.append(
  _GENERATETEMPLATERESPONSE.fields_by_name['error'])
_GENERATETEMPLATERESPONSE.fields_by_name['error'].containing_oneof = _GENERATETEMPLATERESPONSE.oneofs_by_name['content']
_GENERATETEMPLATERESPONSE.oneofs_by_name['content'].fields.append(
  _GENERATETEMPLATERESPONSE.fields_by_name['result'])
_GENERATETEMPLATERESPONSE.fields_by_name['result'].containing_oneof = _GENERATETEMPLATERESPONSE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['GenerateTemplateRequest'] = _GENERATETEMPLATEREQUEST
DESCRIPTOR.message_types_by_name['GenerateTemplateResponse'] = _GENERATETEMPLATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateTemplateRequest = _reflection.GeneratedProtocolMessageType('GenerateTemplateRequest', (_message.Message,), dict(

  KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
    DESCRIPTOR = _GENERATETEMPLATEREQUEST_KEYVALUE,
    __module__ = 'template_pb2'
    # @@protoc_insertion_point(class_scope:template.GenerateTemplateRequest.KeyValue)
    ))
  ,
  DESCRIPTOR = _GENERATETEMPLATEREQUEST,
  __module__ = 'template_pb2'
  # @@protoc_insertion_point(class_scope:template.GenerateTemplateRequest)
  ))
_sym_db.RegisterMessage(GenerateTemplateRequest)
_sym_db.RegisterMessage(GenerateTemplateRequest.KeyValue)

GenerateTemplateResponse = _reflection.GeneratedProtocolMessageType('GenerateTemplateResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERATETEMPLATERESPONSE,
  __module__ = 'template_pb2'
  # @@protoc_insertion_point(class_scope:template.GenerateTemplateResponse)
  ))
_sym_db.RegisterMessage(GenerateTemplateResponse)


# @@protoc_insertion_point(module_scope)
