// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package template

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GenerateTemplateRequest struct {
	TemplateId string                              `protobuf:"bytes,1,opt,name=templateId" json:"templateId,omitempty"`
	Chunk      *GenerateTemplateRequest_Chunk      `protobuf:"bytes,3,opt,name=chunk" json:"chunk,omitempty"`
	Params     []*GenerateTemplateRequest_KeyValue `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
}

func (m *GenerateTemplateRequest) Reset()                    { *m = GenerateTemplateRequest{} }
func (m *GenerateTemplateRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateTemplateRequest) ProtoMessage()               {}
func (*GenerateTemplateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GenerateTemplateRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *GenerateTemplateRequest) GetChunk() *GenerateTemplateRequest_Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *GenerateTemplateRequest) GetParams() []*GenerateTemplateRequest_KeyValue {
	if m != nil {
		return m.Params
	}
	return nil
}

type GenerateTemplateRequest_Chunk struct {
	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Position int64  `protobuf:"varint,2,opt,name=position" json:"position,omitempty"`
}

func (m *GenerateTemplateRequest_Chunk) Reset()         { *m = GenerateTemplateRequest_Chunk{} }
func (m *GenerateTemplateRequest_Chunk) String() string { return proto.CompactTextString(m) }
func (*GenerateTemplateRequest_Chunk) ProtoMessage()    {}
func (*GenerateTemplateRequest_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 0}
}

func (m *GenerateTemplateRequest_Chunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GenerateTemplateRequest_Chunk) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type GenerateTemplateRequest_KeyValue struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *GenerateTemplateRequest_KeyValue) Reset()         { *m = GenerateTemplateRequest_KeyValue{} }
func (m *GenerateTemplateRequest_KeyValue) String() string { return proto.CompactTextString(m) }
func (*GenerateTemplateRequest_KeyValue) ProtoMessage()    {}
func (*GenerateTemplateRequest_KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 1}
}

func (m *GenerateTemplateRequest_KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GenerateTemplateRequest_KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GenerateTemplateResponse struct {
	// Types that are valid to be assigned to Content:
	//	*GenerateTemplateResponse_Error
	//	*GenerateTemplateResponse_Result
	Content isGenerateTemplateResponse_Content `protobuf_oneof:"content"`
}

func (m *GenerateTemplateResponse) Reset()                    { *m = GenerateTemplateResponse{} }
func (m *GenerateTemplateResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateTemplateResponse) ProtoMessage()               {}
func (*GenerateTemplateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isGenerateTemplateResponse_Content interface {
	isGenerateTemplateResponse_Content()
}

type GenerateTemplateResponse_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,oneof"`
}
type GenerateTemplateResponse_Result struct {
	Result string `protobuf:"bytes,2,opt,name=result,oneof"`
}

func (*GenerateTemplateResponse_Error) isGenerateTemplateResponse_Content()  {}
func (*GenerateTemplateResponse_Result) isGenerateTemplateResponse_Content() {}

func (m *GenerateTemplateResponse) GetContent() isGenerateTemplateResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GenerateTemplateResponse) GetError() *Error {
	if x, ok := m.GetContent().(*GenerateTemplateResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *GenerateTemplateResponse) GetResult() string {
	if x, ok := m.GetContent().(*GenerateTemplateResponse_Result); ok {
		return x.Result
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GenerateTemplateResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GenerateTemplateResponse_OneofMarshaler, _GenerateTemplateResponse_OneofUnmarshaler, _GenerateTemplateResponse_OneofSizer, []interface{}{
		(*GenerateTemplateResponse_Error)(nil),
		(*GenerateTemplateResponse_Result)(nil),
	}
}

func _GenerateTemplateResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GenerateTemplateResponse)
	// content
	switch x := m.Content.(type) {
	case *GenerateTemplateResponse_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *GenerateTemplateResponse_Result:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Result)
	case nil:
	default:
		return fmt.Errorf("GenerateTemplateResponse.Content has unexpected type %T", x)
	}
	return nil
}

func _GenerateTemplateResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GenerateTemplateResponse)
	switch tag {
	case 1: // content.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Content = &GenerateTemplateResponse_Error{msg}
		return true, err
	case 2: // content.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Content = &GenerateTemplateResponse_Result{x}
		return true, err
	default:
		return false, nil
	}
}

func _GenerateTemplateResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GenerateTemplateResponse)
	// content
	switch x := m.Content.(type) {
	case *GenerateTemplateResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GenerateTemplateResponse_Result:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Result)))
		n += len(x.Result)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*GenerateTemplateRequest)(nil), "template.GenerateTemplateRequest")
	proto.RegisterType((*GenerateTemplateRequest_Chunk)(nil), "template.GenerateTemplateRequest.Chunk")
	proto.RegisterType((*GenerateTemplateRequest_KeyValue)(nil), "template.GenerateTemplateRequest.KeyValue")
	proto.RegisterType((*GenerateTemplateResponse)(nil), "template.GenerateTemplateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Template service

type TemplateClient interface {
	GenerateTemplate(ctx context.Context, opts ...grpc.CallOption) (Template_GenerateTemplateClient, error)
}

type templateClient struct {
	cc *grpc.ClientConn
}

func NewTemplateClient(cc *grpc.ClientConn) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) GenerateTemplate(ctx context.Context, opts ...grpc.CallOption) (Template_GenerateTemplateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Template_serviceDesc.Streams[0], c.cc, "/template.Template/GenerateTemplate", opts...)
	if err != nil {
		return nil, err
	}
	x := &templateGenerateTemplateClient{stream}
	return x, nil
}

type Template_GenerateTemplateClient interface {
	Send(*GenerateTemplateRequest) error
	CloseAndRecv() (*GenerateTemplateResponse, error)
	grpc.ClientStream
}

type templateGenerateTemplateClient struct {
	grpc.ClientStream
}

func (x *templateGenerateTemplateClient) Send(m *GenerateTemplateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templateGenerateTemplateClient) CloseAndRecv() (*GenerateTemplateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GenerateTemplateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Template service

type TemplateServer interface {
	GenerateTemplate(Template_GenerateTemplateServer) error
}

func RegisterTemplateServer(s *grpc.Server, srv TemplateServer) {
	s.RegisterService(&_Template_serviceDesc, srv)
}

func _Template_GenerateTemplate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplateServer).GenerateTemplate(&templateGenerateTemplateServer{stream})
}

type Template_GenerateTemplateServer interface {
	SendAndClose(*GenerateTemplateResponse) error
	Recv() (*GenerateTemplateRequest, error)
	grpc.ServerStream
}

type templateGenerateTemplateServer struct {
	grpc.ServerStream
}

func (x *templateGenerateTemplateServer) SendAndClose(m *GenerateTemplateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templateGenerateTemplateServer) Recv() (*GenerateTemplateRequest, error) {
	m := new(GenerateTemplateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Template_serviceDesc = grpc.ServiceDesc{
	ServiceName: "template.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateTemplate",
			Handler:       _Template_GenerateTemplate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "template.proto",
}

func init() { proto.RegisterFile("template.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0x6e, 0x9a, 0x37, 0x7d, 0xd3, 0x0b, 0x82, 0xea, 0x84, 0x84, 0x95, 0x01, 0x85, 0x2e, 0x8d,
	0x18, 0x3a, 0x84, 0x81, 0x89, 0xa5, 0x08, 0x51, 0xc4, 0x66, 0x21, 0x16, 0x26, 0xd3, 0x9e, 0x68,
	0xd5, 0xd6, 0x0e, 0xb6, 0x83, 0xd4, 0x9f, 0xc4, 0xbf, 0x44, 0xb1, 0x93, 0x82, 0x40, 0xd0, 0xcd,
	0xcf, 0xdd, 0x3d, 0x1f, 0x77, 0x32, 0x1c, 0x5a, 0xda, 0x94, 0x6b, 0x61, 0x69, 0x5c, 0x6a, 0x65,
	0x15, 0xc6, 0x2d, 0x4e, 0x13, 0xd2, 0x5a, 0x69, 0x5f, 0x1e, 0xbe, 0x77, 0xe1, 0xe4, 0x96, 0x24,
	0x69, 0x61, 0xe9, 0xa1, 0x99, 0xe0, 0xf4, 0x5a, 0x91, 0xb1, 0x78, 0x0a, 0xd0, 0x92, 0xee, 0xe6,
	0x2c, 0xc8, 0x82, 0xbc, 0xcf, 0xbf, 0x54, 0xf0, 0x0a, 0xa2, 0xd9, 0xa2, 0x92, 0x2b, 0x16, 0x66,
	0x41, 0x9e, 0x14, 0xa3, 0xf1, 0xce, 0xf2, 0x17, 0xc5, 0xf1, 0x75, 0x3d, 0xce, 0x3d, 0x0b, 0x27,
	0xd0, 0x2b, 0x85, 0x16, 0x1b, 0xc3, 0xba, 0x59, 0x98, 0x27, 0xc5, 0xf9, 0x7e, 0xfe, 0x3d, 0x6d,
	0x1f, 0xc5, 0xba, 0x22, 0xde, 0x30, 0xd3, 0x4b, 0x88, 0x9c, 0x26, 0x22, 0xfc, 0x9b, 0x0b, 0x2b,
	0x5c, 0xca, 0x03, 0xee, 0xde, 0x98, 0x42, 0x5c, 0x2a, 0xb3, 0xb4, 0x4b, 0x25, 0x59, 0x37, 0x0b,
	0xf2, 0x90, 0xef, 0x70, 0x5a, 0x40, 0xdc, 0x8a, 0xe1, 0x00, 0xc2, 0x15, 0x6d, 0x9b, 0x05, 0xeb,
	0x27, 0x1e, 0x43, 0xf4, 0x56, 0xb7, 0x1c, 0xad, 0xcf, 0x3d, 0x18, 0x2e, 0x80, 0xfd, 0x0c, 0x66,
	0x4a, 0x25, 0x0d, 0xe1, 0x08, 0x22, 0x77, 0x56, 0xa7, 0x92, 0x14, 0x47, 0x9f, 0xbb, 0xdc, 0xd4,
	0xe5, 0x69, 0x87, 0xfb, 0x3e, 0x32, 0xe8, 0x69, 0x32, 0xd5, 0xda, 0x7a, 0xed, 0x69, 0x87, 0x37,
	0x78, 0xd2, 0x87, 0xff, 0x33, 0x25, 0x2d, 0x49, 0x5b, 0xbc, 0x40, 0xdc, 0x3a, 0xe0, 0x13, 0x0c,
	0xbe, 0xbb, 0xe2, 0xd9, 0xde, 0x53, 0xa5, 0xc3, 0xbf, 0x46, 0x7c, 0xe8, 0x3c, 0x78, 0xee, 0xb9,
	0x5f, 0x70, 0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x17, 0xa4, 0xba, 0x2e, 0x02, 0x00, 0x00,
}
